import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Wifi, WifiOff, ArrowDown, ArrowUp, Calendar, Monitor } from 'lucide-react';
import { useApi } from '../hooks/useApi';
import { conexaoService } from '../services/api';
import { StatusBadge } from '../components/ui/StatusBadge';
import { PageLoader } from '../components/ui/Spinner';
import { Alert } from '../components/ui/Alert';
function formatarData(d) {
    return new Date(d + 'T00:00:00').toLocaleDateString('pt-BR');
}
export function ConexaoPage() {
    const { data: conexao, isLoading, erro, refetch } = useApi(conexaoService.status);
    return (_jsxs("div", { className: "space-y-6 animate-fade-in", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "font-display text-3xl font-700 text-white", children: "Conex\u00E3o" }), _jsx("p", { className: "text-slate-400 text-sm mt-1", children: "Status e informa\u00E7\u00F5es do seu plano" })] }), _jsx("button", { onClick: refetch, className: "btn-secondary text-sm px-4 py-2", children: "Atualizar" })] }), erro && _jsx(Alert, { tipo: "erro", mensagem: erro }), isLoading && _jsx(PageLoader, {}), conexao && (_jsxs(_Fragment, { children: [_jsx("div", { className: "card p-6 animate-slide-up", children: _jsxs("div", { className: "flex items-center gap-5", children: [_jsx("div", { className: `w-16 h-16 rounded-2xl flex items-center justify-center shrink-0 ${conexao.status === 'online'
                                        ? 'bg-emerald-500/15'
                                        : conexao.status === 'suspenso'
                                            ? 'bg-red-500/15'
                                            : 'bg-slate-700/40'}`, children: conexao.status === 'online'
                                        ? _jsx(Wifi, { size: 28, className: "text-emerald-400" })
                                        : _jsx(WifiOff, { size: 28, className: "text-red-400" }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-3 mb-1", children: [_jsx("h2", { className: "font-display font-700 text-white text-xl", children: conexao.status === 'online' ? 'Conexão ativa' : conexao.status === 'suspenso' ? 'Conexão suspensa' : 'Sem conexão' }), _jsx(StatusBadge, { status: conexao.status, tipo: "conexao" })] }), _jsx("p", { className: "text-slate-400 text-sm", children: conexao.status === 'online'
                                                ? 'Sua internet está funcionando normalmente.'
                                                : conexao.status === 'suspenso'
                                                    ? 'Pague suas faturas em aberto para reativar.'
                                                    : 'Verifique seu equipamento ou contate o suporte.' })] })] }) }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4", children: [conexao.plano && (_jsxs("div", { className: "card p-5 animate-slide-up delay-100", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(Monitor, { size: 16, className: "text-brand-400" }), _jsx("p", { className: "text-slate-400 text-xs font-medium uppercase tracking-wide", children: "Plano" })] }), _jsx("p", { className: "text-white font-display font-700 text-lg", children: conexao.plano })] })), conexao.vencimento && (_jsxs("div", { className: "card p-5 animate-slide-up delay-200", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(Calendar, { size: 16, className: "text-amber-400" }), _jsx("p", { className: "text-slate-400 text-xs font-medium uppercase tracking-wide", children: "Vencimento" })] }), _jsx("p", { className: "text-white font-display font-700 text-lg", children: formatarData(conexao.vencimento) })] })), conexao.download && (_jsxs("div", { className: "card p-5 animate-slide-up delay-300", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(ArrowDown, { size: 16, className: "text-emerald-400" }), _jsx("p", { className: "text-slate-400 text-xs font-medium uppercase tracking-wide", children: "Download" })] }), _jsx("p", { className: "text-white font-display font-700 text-lg", children: conexao.download })] })), conexao.upload && (_jsxs("div", { className: "card p-5 animate-slide-up delay-400", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(ArrowUp, { size: 16, className: "text-brand-400" }), _jsx("p", { className: "text-slate-400 text-xs font-medium uppercase tracking-wide", children: "Upload" })] }), _jsx("p", { className: "text-white font-display font-700 text-lg", children: conexao.upload })] }))] }), conexao.ip && (_jsxs("div", { className: "card p-5 animate-slide-up", children: [_jsx("p", { className: "text-slate-400 text-xs mb-1", children: "Endere\u00E7o IP" }), _jsx("p", { className: "text-slate-300 font-mono text-sm", children: conexao.ip })] }))] }))] }));
}
